import type { Scenario } from './types'

export const scenarios: Scenario[] = [
  {
    id: 'setTimeout-promise',
    title: 'setTimeout vs Promise',
    code: `console.log('1: Start')

setTimeout(() => {
  console.log('2: setTimeout')
}, 0)

Promise.resolve().then(() => {
  console.log('3: Promise')
})

console.log('4: End')`,
    steps: [
      {
        description: 'Bắt đầu thực thi script — toàn bộ script được đẩy vào Call Stack như một macrotask.',
        highlightLines: [],
        callStack: [{ id: 'script', label: 'Script' }],
        taskQueue: [],
        microtaskQueue: [],
        rafQueue: [],
        phase: 'macrotask',
        consoleOutput: [],
        webAPIs: [],
      },
      {
        description: 'console.log("1: Start") — thực thi đồng bộ, in ra console ngay.',
        highlightLines: [1],
        callStack: [{ id: 'script', label: 'Script' }, { id: 'log1', label: 'console.log' }],
        taskQueue: [],
        microtaskQueue: [],
        rafQueue: [],
        phase: 'macrotask',
        consoleOutput: ['1: Start'],
        webAPIs: [],
      },
      {
        description: 'setTimeout(fn, 0) — browser đăng ký timer với Web API. Callback chưa vào queue.',
        highlightLines: [3, 4, 5],
        callStack: [{ id: 'script', label: 'Script' }, { id: 'st', label: 'setTimeout' }],
        taskQueue: [],
        microtaskQueue: [],
        rafQueue: [],
        phase: 'macrotask',
        consoleOutput: ['1: Start'],
        webAPIs: [{ id: 'timer', label: 'Timer (0ms)' }],
      },
      {
        description: 'setTimeout pop khỏi Call Stack. Timer hết hạn → callback được đẩy vào Task Queue.',
        highlightLines: [3, 4, 5],
        callStack: [{ id: 'script', label: 'Script' }],
        taskQueue: [{ id: 'st-cb', label: 'setTimeout cb' }],
        microtaskQueue: [],
        rafQueue: [],
        phase: 'macrotask',
        consoleOutput: ['1: Start'],
        webAPIs: [],
      },
      {
        description: 'Promise.resolve().then(fn) — Promise đã resolved, callback được đẩy thẳng vào Microtask Queue.',
        highlightLines: [7, 8, 9],
        callStack: [{ id: 'script', label: 'Script' }, { id: 'promise', label: 'Promise.then' }],
        taskQueue: [{ id: 'st-cb', label: 'setTimeout cb' }],
        microtaskQueue: [{ id: 'p-cb', label: 'Promise cb' }],
        rafQueue: [],
        phase: 'macrotask',
        consoleOutput: ['1: Start'],
        webAPIs: [],
      },
      {
        description: 'console.log("4: End") — thực thi đồng bộ, in ra console ngay.',
        highlightLines: [11],
        callStack: [{ id: 'script', label: 'Script' }, { id: 'log4', label: 'console.log' }],
        taskQueue: [{ id: 'st-cb', label: 'setTimeout cb' }],
        microtaskQueue: [{ id: 'p-cb', label: 'Promise cb' }],
        rafQueue: [],
        phase: 'macrotask',
        consoleOutput: ['1: Start', '4: End'],
        webAPIs: [],
      },
      {
        description: 'Script thực thi xong, pop khỏi Call Stack. Call Stack trống → Event Loop kiểm tra Microtask Queue.',
        highlightLines: [],
        callStack: [],
        taskQueue: [{ id: 'st-cb', label: 'setTimeout cb' }],
        microtaskQueue: [{ id: 'p-cb', label: 'Promise cb' }],
        rafQueue: [],
        phase: 'microtask',
        consoleOutput: ['1: Start', '4: End'],
        webAPIs: [],
      },
      {
        description: 'Drain Microtask Queue — Promise callback được lấy ra và đẩy vào Call Stack. In "3: Promise".',
        highlightLines: [8],
        callStack: [{ id: 'p-cb', label: 'Promise cb' }],
        taskQueue: [{ id: 'st-cb', label: 'setTimeout cb' }],
        microtaskQueue: [],
        rafQueue: [],
        phase: 'microtask',
        consoleOutput: ['1: Start', '4: End', '3: Promise'],
        webAPIs: [],
      },
      {
        description: 'Microtask Queue rỗng. Render nếu cần → quay lại lấy macrotask tiếp theo từ Task Queue.',
        highlightLines: [],
        callStack: [],
        taskQueue: [{ id: 'st-cb', label: 'setTimeout cb' }],
        microtaskQueue: [],
        rafQueue: [],
        phase: 'macrotask',
        consoleOutput: ['1: Start', '4: End', '3: Promise'],
        webAPIs: [],
      },
      {
        description: 'Lấy setTimeout callback từ Task Queue → đẩy vào Call Stack. In "2: setTimeout".',
        highlightLines: [4],
        callStack: [{ id: 'st-cb', label: 'setTimeout cb' }],
        taskQueue: [],
        microtaskQueue: [],
        rafQueue: [],
        phase: 'macrotask',
        consoleOutput: ['1: Start', '4: End', '3: Promise', '2: setTimeout'],
        webAPIs: [],
      },
      {
        description: 'Hoàn tất! Thứ tự: Start → End → Promise → setTimeout. Microtask luôn chạy trước Macrotask.',
        highlightLines: [],
        callStack: [],
        taskQueue: [],
        microtaskQueue: [],
        rafQueue: [],
        phase: 'idle',
        consoleOutput: ['1: Start', '4: End', '3: Promise', '2: setTimeout'],
        webAPIs: [],
      },
    ],
  },
  {
    id: 'microtask-chain',
    title: 'Microtask chain',
    code: `console.log('Start')

setTimeout(() => {
  console.log('Timeout')
}, 0)

Promise.resolve()
  .then(() => {
    console.log('Promise 1')
    return Promise.resolve()
  })
  .then(() => {
    console.log('Promise 2')
  })

console.log('End')`,
    steps: [
      {
        description: 'Bắt đầu thực thi script.',
        highlightLines: [],
        callStack: [{ id: 'script', label: 'Script' }],
        taskQueue: [],
        microtaskQueue: [],
        rafQueue: [],
        phase: 'macrotask',
        consoleOutput: [],
        webAPIs: [],
      },
      {
        description: 'console.log("Start") — in ra console.',
        highlightLines: [1],
        callStack: [{ id: 'script', label: 'Script' }, { id: 'log1', label: 'console.log' }],
        taskQueue: [],
        microtaskQueue: [],
        rafQueue: [],
        phase: 'macrotask',
        consoleOutput: ['Start'],
        webAPIs: [],
      },
      {
        description: 'setTimeout đăng ký timer → callback vào Task Queue.',
        highlightLines: [3, 4, 5],
        callStack: [{ id: 'script', label: 'Script' }],
        taskQueue: [{ id: 'st-cb', label: 'setTimeout cb' }],
        microtaskQueue: [],
        rafQueue: [],
        phase: 'macrotask',
        consoleOutput: ['Start'],
        webAPIs: [],
      },
      {
        description: 'Promise.resolve().then(fn1).then(fn2) — fn1 vào Microtask Queue. fn2 chưa schedule (chờ fn1 resolve).',
        highlightLines: [7, 8, 9, 10, 11, 12, 13, 14],
        callStack: [{ id: 'script', label: 'Script' }],
        taskQueue: [{ id: 'st-cb', label: 'setTimeout cb' }],
        microtaskQueue: [{ id: 'p1', label: 'then(fn1)' }],
        rafQueue: [],
        phase: 'macrotask',
        consoleOutput: ['Start'],
        webAPIs: [],
      },
      {
        description: 'console.log("End") — in ra console. Script thực thi xong.',
        highlightLines: [16],
        callStack: [{ id: 'script', label: 'Script' }, { id: 'log2', label: 'console.log' }],
        taskQueue: [{ id: 'st-cb', label: 'setTimeout cb' }],
        microtaskQueue: [{ id: 'p1', label: 'then(fn1)' }],
        rafQueue: [],
        phase: 'macrotask',
        consoleOutput: ['Start', 'End'],
        webAPIs: [],
      },
      {
        description: 'Script pop khỏi Call Stack → drain Microtask Queue. fn1 chạy, in "Promise 1", return Promise.resolve().',
        highlightLines: [9, 10],
        callStack: [{ id: 'p1', label: 'then(fn1)' }],
        taskQueue: [{ id: 'st-cb', label: 'setTimeout cb' }],
        microtaskQueue: [],
        rafQueue: [],
        phase: 'microtask',
        consoleOutput: ['Start', 'End', 'Promise 1'],
        webAPIs: [],
      },
      {
        description: 'fn1 resolve → fn2 được schedule vào Microtask Queue. Vẫn đang drain microtask!',
        highlightLines: [10],
        callStack: [],
        taskQueue: [{ id: 'st-cb', label: 'setTimeout cb' }],
        microtaskQueue: [{ id: 'p2', label: 'then(fn2)' }],
        rafQueue: [],
        phase: 'microtask',
        consoleOutput: ['Start', 'End', 'Promise 1'],
        webAPIs: [],
      },
      {
        description: 'Microtask Queue chưa rỗng! fn2 chạy, in "Promise 2". Microtask drain kể cả các microtask sinh ra trong quá trình.',
        highlightLines: [13],
        callStack: [{ id: 'p2', label: 'then(fn2)' }],
        taskQueue: [{ id: 'st-cb', label: 'setTimeout cb' }],
        microtaskQueue: [],
        rafQueue: [],
        phase: 'microtask',
        consoleOutput: ['Start', 'End', 'Promise 1', 'Promise 2'],
        webAPIs: [],
      },
      {
        description: 'Microtask Queue rỗng → lấy macrotask. setTimeout callback chạy, in "Timeout".',
        highlightLines: [4],
        callStack: [{ id: 'st-cb', label: 'setTimeout cb' }],
        taskQueue: [],
        microtaskQueue: [],
        rafQueue: [],
        phase: 'macrotask',
        consoleOutput: ['Start', 'End', 'Promise 1', 'Promise 2', 'Timeout'],
        webAPIs: [],
      },
      {
        description: 'Hoàn tất! Promise chain drain hết trước khi setTimeout chạy — microtask có độ ưu tiên cao hơn.',
        highlightLines: [],
        callStack: [],
        taskQueue: [],
        microtaskQueue: [],
        rafQueue: [],
        phase: 'idle',
        consoleOutput: ['Start', 'End', 'Promise 1', 'Promise 2', 'Timeout'],
        webAPIs: [],
      },
    ],
  },
  {
    id: 'raf-render',
    title: 'requestAnimationFrame',
    code: `console.log('Start')

requestAnimationFrame(() => {
  console.log('rAF callback')
})

setTimeout(() => {
  console.log('Timeout')
}, 0)

Promise.resolve().then(() => {
  console.log('Promise')
})

console.log('End')`,
    steps: [
      {
        description: 'Bắt đầu thực thi script.',
        highlightLines: [],
        callStack: [{ id: 'script', label: 'Script' }],
        taskQueue: [],
        microtaskQueue: [],
        rafQueue: [],
        phase: 'macrotask',
        consoleOutput: [],
        webAPIs: [],
      },
      {
        description: 'console.log("Start") — in ra console.',
        highlightLines: [1],
        callStack: [{ id: 'script', label: 'Script' }, { id: 'log1', label: 'console.log' }],
        taskQueue: [],
        microtaskQueue: [],
        rafQueue: [],
        phase: 'macrotask',
        consoleOutput: ['Start'],
        webAPIs: [],
      },
      {
        description: 'requestAnimationFrame(fn) — callback được schedule để chạy trước frame render tiếp theo.',
        highlightLines: [3, 4, 5],
        callStack: [{ id: 'script', label: 'Script' }],
        taskQueue: [],
        microtaskQueue: [],
        rafQueue: [{ id: 'raf', label: 'rAF cb' }],
        phase: 'macrotask',
        consoleOutput: ['Start'],
        webAPIs: [],
      },
      {
        description: 'setTimeout(fn, 0) → callback vào Task Queue.',
        highlightLines: [7, 8, 9],
        callStack: [{ id: 'script', label: 'Script' }],
        taskQueue: [{ id: 'st-cb', label: 'setTimeout cb' }],
        microtaskQueue: [],
        rafQueue: [{ id: 'raf', label: 'rAF cb' }],
        phase: 'macrotask',
        consoleOutput: ['Start'],
        webAPIs: [],
      },
      {
        description: 'Promise.resolve().then(fn) → callback vào Microtask Queue.',
        highlightLines: [11, 12, 13],
        callStack: [{ id: 'script', label: 'Script' }],
        taskQueue: [{ id: 'st-cb', label: 'setTimeout cb' }],
        microtaskQueue: [{ id: 'p-cb', label: 'Promise cb' }],
        rafQueue: [{ id: 'raf', label: 'rAF cb' }],
        phase: 'macrotask',
        consoleOutput: ['Start'],
        webAPIs: [],
      },
      {
        description: 'console.log("End") — in ra console. Script xong.',
        highlightLines: [15],
        callStack: [{ id: 'script', label: 'Script' }, { id: 'log2', label: 'console.log' }],
        taskQueue: [{ id: 'st-cb', label: 'setTimeout cb' }],
        microtaskQueue: [{ id: 'p-cb', label: 'Promise cb' }],
        rafQueue: [{ id: 'raf', label: 'rAF cb' }],
        phase: 'macrotask',
        consoleOutput: ['Start', 'End'],
        webAPIs: [],
      },
      {
        description: 'Script pop → drain Microtask Queue trước. Promise callback chạy, in "Promise".',
        highlightLines: [12],
        callStack: [{ id: 'p-cb', label: 'Promise cb' }],
        taskQueue: [{ id: 'st-cb', label: 'setTimeout cb' }],
        microtaskQueue: [],
        rafQueue: [{ id: 'raf', label: 'rAF cb' }],
        phase: 'microtask',
        consoleOutput: ['Start', 'End', 'Promise'],
        webAPIs: [],
      },
      {
        description: 'Microtask rỗng → chạy rAF callbacks trước khi render. In "rAF callback".',
        highlightLines: [4],
        callStack: [{ id: 'raf', label: 'rAF cb' }],
        taskQueue: [{ id: 'st-cb', label: 'setTimeout cb' }],
        microtaskQueue: [],
        rafQueue: [],
        phase: 'raf',
        consoleOutput: ['Start', 'End', 'Promise', 'rAF callback'],
        webAPIs: [],
      },
      {
        description: 'Browser thực hiện Render: Style → Layout → Paint → Composite.',
        highlightLines: [],
        callStack: [],
        taskQueue: [{ id: 'st-cb', label: 'setTimeout cb' }],
        microtaskQueue: [],
        rafQueue: [],
        phase: 'render',
        consoleOutput: ['Start', 'End', 'Promise', 'rAF callback'],
        webAPIs: [],
      },
      {
        description: 'Render xong → lấy macrotask tiếp theo. setTimeout callback chạy, in "Timeout".',
        highlightLines: [8],
        callStack: [{ id: 'st-cb', label: 'setTimeout cb' }],
        taskQueue: [],
        microtaskQueue: [],
        rafQueue: [],
        phase: 'macrotask',
        consoleOutput: ['Start', 'End', 'Promise', 'rAF callback', 'Timeout'],
        webAPIs: [],
      },
      {
        description: 'Hoàn tất! Thứ tự: Microtask → rAF → Render → Macrotask. rAF luôn chạy trước render.',
        highlightLines: [],
        callStack: [],
        taskQueue: [],
        microtaskQueue: [],
        rafQueue: [],
        phase: 'idle',
        consoleOutput: ['Start', 'End', 'Promise', 'rAF callback', 'Timeout'],
        webAPIs: [],
      },
    ],
  },
]
