import type { NodejsScenario } from './types'

export const scenarios: NodejsScenario[] = [
  {
    id: 'nexttick-vs-promise',
    title: 'process.nextTick vs Promise',
    code: `console.log('Start')

process.nextTick(() => {
  console.log('nextTick')
})

Promise.resolve().then(() => {
  console.log('Promise')
})

queueMicrotask(() => {
  console.log('queueMicrotask')
})

console.log('End')`,
    steps: [
      {
        description: 'Bắt đầu thực thi script — Node.js chạy module trước khi event loop bắt đầu.',
        highlightLines: [],
        callStack: [{ id: 'script', label: 'Module' }],
        nextTickQueue: [],
        microtaskQueue: [],
        timerQueue: [],
        checkQueue: [],
        phase: 'idle',
        consoleOutput: [],
        libuvOps: [],
      },
      {
        description: 'console.log("Start") — thực thi đồng bộ, in ra console ngay.',
        highlightLines: [1],
        callStack: [{ id: 'script', label: 'Module' }, { id: 'log1', label: 'console.log' }],
        nextTickQueue: [],
        microtaskQueue: [],
        timerQueue: [],
        checkQueue: [],
        phase: 'idle',
        consoleOutput: ['Start'],
        libuvOps: [],
      },
      {
        description: 'process.nextTick(fn) — callback được đẩy vào nextTick queue (KHÔNG phải microtask queue).',
        highlightLines: [3, 4, 5],
        callStack: [{ id: 'script', label: 'Module' }, { id: 'nt', label: 'process.nextTick' }],
        nextTickQueue: [{ id: 'nt-cb', label: '() => log("nextTick")' }],
        microtaskQueue: [],
        timerQueue: [],
        checkQueue: [],
        phase: 'idle',
        consoleOutput: ['Start'],
        libuvOps: [],
      },
      {
        description: 'Promise.resolve().then(fn) — callback được đẩy vào microtask queue.',
        highlightLines: [7, 8, 9],
        callStack: [{ id: 'script', label: 'Module' }, { id: 'pr', label: 'Promise.then' }],
        nextTickQueue: [{ id: 'nt-cb', label: '() => log("nextTick")' }],
        microtaskQueue: [{ id: 'pr-cb', label: '() => log("Promise")' }],
        timerQueue: [],
        checkQueue: [],
        phase: 'idle',
        consoleOutput: ['Start'],
        libuvOps: [],
      },
      {
        description: 'queueMicrotask(fn) — callback cũng vào microtask queue, sau Promise callback.',
        highlightLines: [11, 12, 13],
        callStack: [{ id: 'script', label: 'Module' }, { id: 'qm', label: 'queueMicrotask' }],
        nextTickQueue: [{ id: 'nt-cb', label: '() => log("nextTick")' }],
        microtaskQueue: [
          { id: 'pr-cb', label: '() => log("Promise")' },
          { id: 'qm-cb', label: '() => log("queueMicrotask")' },
        ],
        timerQueue: [],
        checkQueue: [],
        phase: 'idle',
        consoleOutput: ['Start'],
        libuvOps: [],
      },
      {
        description: 'console.log("End") — thực thi đồng bộ, in ra console.',
        highlightLines: [15],
        callStack: [{ id: 'script', label: 'Module' }, { id: 'log2', label: 'console.log' }],
        nextTickQueue: [{ id: 'nt-cb', label: '() => log("nextTick")' }],
        microtaskQueue: [
          { id: 'pr-cb', label: '() => log("Promise")' },
          { id: 'qm-cb', label: '() => log("queueMicrotask")' },
        ],
        timerQueue: [],
        checkQueue: [],
        phase: 'idle',
        consoleOutput: ['Start', 'End'],
        libuvOps: [],
      },
      {
        description: 'Script xong. Trước khi event loop bắt đầu vòng đầu tiên (từ Timers), Node.js drain nextTick queue TRƯỚC.',
        highlightLines: [],
        callStack: [],
        nextTickQueue: [{ id: 'nt-cb', label: '() => log("nextTick")' }],
        microtaskQueue: [
          { id: 'pr-cb', label: '() => log("Promise")' },
          { id: 'qm-cb', label: '() => log("queueMicrotask")' },
        ],
        timerQueue: [],
        checkQueue: [],
        phase: 'between-phases',
        consoleOutput: ['Start', 'End'],
        libuvOps: [],
        drainingNextTick: true,
      },
      {
        description: 'Drain nextTick: chạy callback → in "nextTick". nextTick queue giờ rỗng.',
        highlightLines: [4],
        callStack: [{ id: 'nt-cb', label: '() => log("nextTick")' }],
        nextTickQueue: [],
        microtaskQueue: [
          { id: 'pr-cb', label: '() => log("Promise")' },
          { id: 'qm-cb', label: '() => log("queueMicrotask")' },
        ],
        timerQueue: [],
        checkQueue: [],
        phase: 'between-phases',
        consoleOutput: ['Start', 'End', 'nextTick'],
        libuvOps: [],
        drainingNextTick: true,
      },
      {
        description: 'nextTick queue rỗng → chuyển sang drain microtask queue. Chạy Promise callback → in "Promise".',
        highlightLines: [8],
        callStack: [{ id: 'pr-cb', label: '() => log("Promise")' }],
        nextTickQueue: [],
        microtaskQueue: [{ id: 'qm-cb', label: '() => log("queueMicrotask")' }],
        timerQueue: [],
        checkQueue: [],
        phase: 'between-phases',
        consoleOutput: ['Start', 'End', 'nextTick', 'Promise'],
        libuvOps: [],
        drainingMicrotask: true,
      },
      {
        description: 'Tiếp tục drain microtask: chạy queueMicrotask callback → in "queueMicrotask".',
        highlightLines: [12],
        callStack: [{ id: 'qm-cb', label: '() => log("queueMicrotask")' }],
        nextTickQueue: [],
        microtaskQueue: [],
        timerQueue: [],
        checkQueue: [],
        phase: 'between-phases',
        consoleOutput: ['Start', 'End', 'nextTick', 'Promise', 'queueMicrotask'],
        libuvOps: [],
        drainingMicrotask: true,
      },
      {
        description: 'Cả hai queue đều rỗng. Event loop tiếp tục sang phase tiếp theo. Kết quả: nextTick luôn chạy trước Promise vì Node.js drain nextTick queue trước microtask queue.',
        highlightLines: [],
        callStack: [],
        nextTickQueue: [],
        microtaskQueue: [],
        timerQueue: [],
        checkQueue: [],
        phase: 'idle',
        consoleOutput: ['Start', 'End', 'nextTick', 'Promise', 'queueMicrotask'],
        libuvOps: [],
      },
    ],
  },
  {
    id: 'settimeout-vs-setimmediate',
    title: 'setTimeout vs setImmediate',
    code: `setTimeout(() => {
  console.log('setTimeout')
}, 0)

setImmediate(() => {
  console.log('setImmediate')
})`,
    steps: [
      {
        description: 'Bắt đầu thực thi script — chạy trước khi event loop bắt đầu.',
        highlightLines: [],
        callStack: [{ id: 'script', label: 'Module' }],
        nextTickQueue: [],
        microtaskQueue: [],
        timerQueue: [],
        checkQueue: [],
        phase: 'idle',
        consoleOutput: [],
        libuvOps: [],
      },
      {
        description: 'setTimeout(fn, 0) — đăng ký timer với libuv. Thực tế delay tối thiểu ~1ms, không phải 0ms.',
        highlightLines: [1, 2, 3],
        callStack: [{ id: 'script', label: 'Module' }, { id: 'st', label: 'setTimeout' }],
        nextTickQueue: [],
        microtaskQueue: [],
        timerQueue: [],
        checkQueue: [],
        phase: 'idle',
        consoleOutput: [],
        libuvOps: [{ id: 'timer', label: 'Timer (~1ms)' }],
      },
      {
        description: 'setImmediate(fn) — callback đẩy thẳng vào Check queue.',
        highlightLines: [5, 6, 7],
        callStack: [{ id: 'script', label: 'Module' }, { id: 'si', label: 'setImmediate' }],
        nextTickQueue: [],
        microtaskQueue: [],
        timerQueue: [],
        checkQueue: [{ id: 'si-cb', label: '() => log("setImmediate")' }],
        phase: 'idle',
        consoleOutput: [],
        libuvOps: [{ id: 'timer', label: 'Timer (~1ms)' }],
      },
      {
        description: 'Script xong. Event loop bắt đầu vòng mới từ phase Timers. Timer đã hết hạn chưa? Phụ thuộc vào tốc độ hệ thống!',
        highlightLines: [],
        callStack: [],
        nextTickQueue: [],
        microtaskQueue: [],
        timerQueue: [],
        checkQueue: [{ id: 'si-cb', label: '() => log("setImmediate")' }],
        phase: 'between-phases',
        consoleOutput: [],
        libuvOps: [{ id: 'timer', label: 'Timer (~1ms)' }],
      },
      {
        description: '⚡ Trường hợp 1: Timer hết hạn kịp → setTimeout callback vào Timer queue và chạy TRƯỚC.',
        highlightLines: [2],
        callStack: [{ id: 'st-cb', label: '() => log("setTimeout")' }],
        nextTickQueue: [],
        microtaskQueue: [],
        timerQueue: [],
        checkQueue: [{ id: 'si-cb', label: '() => log("setImmediate")' }],
        phase: 'timers',
        consoleOutput: ['setTimeout'],
        libuvOps: [],
      },
      {
        description: 'Phase Check: setImmediate callback chạy → in "setImmediate". Kết quả: setTimeout → setImmediate.',
        highlightLines: [6],
        callStack: [{ id: 'si-cb', label: '() => log("setImmediate")' }],
        nextTickQueue: [],
        microtaskQueue: [],
        timerQueue: [],
        checkQueue: [],
        phase: 'check',
        consoleOutput: ['setTimeout', 'setImmediate'],
        libuvOps: [],
      },
      {
        description: '⚡ Trường hợp 2: Timer CHƯA hết hạn khi vào Timers phase → bỏ qua, chạy tiếp đến Check phase.',
        highlightLines: [6],
        callStack: [{ id: 'si-cb', label: '() => log("setImmediate")' }],
        nextTickQueue: [],
        microtaskQueue: [],
        timerQueue: [],
        checkQueue: [],
        phase: 'check',
        consoleOutput: ['setImmediate'],
        libuvOps: [{ id: 'timer', label: 'Timer (~1ms)' }],
      },
      {
        description: 'Vòng tiếp: timer đã hết hạn → setTimeout callback chạy. Kết quả: setImmediate → setTimeout.',
        highlightLines: [2],
        callStack: [{ id: 'st-cb', label: '() => log("setTimeout")' }],
        nextTickQueue: [],
        microtaskQueue: [],
        timerQueue: [],
        checkQueue: [],
        phase: 'timers',
        consoleOutput: ['setImmediate', 'setTimeout'],
        libuvOps: [],
      },
      {
        description: 'Kết luận: ở top-level, thứ tự setTimeout vs setImmediate KHÔNG XÁC ĐỊNH — phụ thuộc vào timer resolution của hệ thống (~1ms). Bạn không nên viết code dựa vào thứ tự này.',
        highlightLines: [],
        callStack: [],
        nextTickQueue: [],
        microtaskQueue: [],
        timerQueue: [],
        checkQueue: [],
        phase: 'idle',
        consoleOutput: ['setImmediate', 'setTimeout'],
        libuvOps: [],
      },
    ],
  },
  {
    id: 'setimmediate-in-io',
    title: 'setImmediate trong I/O callback',
    code: `const fs = require('fs')

fs.readFile(__filename, () => {
  setTimeout(() => {
    console.log('setTimeout')
  }, 0)

  setImmediate(() => {
    console.log('setImmediate')
  })
})`,
    steps: [
      {
        description: 'Bắt đầu thực thi script — chạy trước khi event loop bắt đầu.',
        highlightLines: [],
        callStack: [{ id: 'script', label: 'Module' }],
        nextTickQueue: [],
        microtaskQueue: [],
        timerQueue: [],
        checkQueue: [],
        phase: 'idle',
        consoleOutput: [],
        libuvOps: [],
      },
      {
        description: 'fs.readFile() — đăng ký I/O operation với libuv. OS sẽ đọc file trong background.',
        highlightLines: [3],
        callStack: [{ id: 'script', label: 'Module' }, { id: 'rf', label: 'fs.readFile' }],
        nextTickQueue: [],
        microtaskQueue: [],
        timerQueue: [],
        checkQueue: [],
        phase: 'idle',
        consoleOutput: [],
        libuvOps: [{ id: 'io', label: 'readFile (pending)' }],
      },
      {
        description: 'Script xong. Event loop bắt đầu, đến Poll phase — chờ I/O events từ OS.',
        highlightLines: [],
        callStack: [],
        nextTickQueue: [],
        microtaskQueue: [],
        timerQueue: [],
        checkQueue: [],
        phase: 'poll',
        consoleOutput: [],
        libuvOps: [{ id: 'io', label: 'readFile (pending)' }],
      },
      {
        description: 'I/O hoàn thành! OS báo libuv → readFile callback sẵn sàng. Thực thi trong Poll phase.',
        highlightLines: [3],
        callStack: [{ id: 'rf-cb', label: 'readFile callback' }],
        nextTickQueue: [],
        microtaskQueue: [],
        timerQueue: [],
        checkQueue: [],
        phase: 'poll',
        consoleOutput: [],
        libuvOps: [],
      },
      {
        description: 'Bên trong callback: setTimeout(fn, 0) — đăng ký timer với libuv.',
        highlightLines: [4, 5, 6],
        callStack: [{ id: 'rf-cb', label: 'readFile callback' }, { id: 'st', label: 'setTimeout' }],
        nextTickQueue: [],
        microtaskQueue: [],
        timerQueue: [],
        checkQueue: [],
        phase: 'poll',
        consoleOutput: [],
        libuvOps: [{ id: 'timer', label: 'Timer (~1ms)' }],
      },
      {
        description: 'Bên trong callback: setImmediate(fn) — callback đẩy vào Check queue.',
        highlightLines: [8, 9, 10],
        callStack: [{ id: 'rf-cb', label: 'readFile callback' }, { id: 'si', label: 'setImmediate' }],
        nextTickQueue: [],
        microtaskQueue: [],
        timerQueue: [],
        checkQueue: [{ id: 'si-cb', label: '() => log("setImmediate")' }],
        phase: 'poll',
        consoleOutput: [],
        libuvOps: [{ id: 'timer', label: 'Timer (~1ms)' }],
      },
      {
        description: 'readFile callback xong. Poll phase kết thúc → event loop tiến sang phase tiếp theo: Check.',
        highlightLines: [],
        callStack: [],
        nextTickQueue: [],
        microtaskQueue: [],
        timerQueue: [],
        checkQueue: [{ id: 'si-cb', label: '() => log("setImmediate")' }],
        phase: 'between-phases',
        consoleOutput: [],
        libuvOps: [{ id: 'timer', label: 'Timer (~1ms)' }],
      },
      {
        description: 'Check phase: setImmediate callback chạy → in "setImmediate". Check phase nằm NGAY SAU Poll — nên setImmediate LUÔN chạy trước.',
        highlightLines: [9],
        callStack: [{ id: 'si-cb', label: '() => log("setImmediate")' }],
        nextTickQueue: [],
        microtaskQueue: [],
        timerQueue: [],
        checkQueue: [],
        phase: 'check',
        consoleOutput: ['setImmediate'],
        libuvOps: [{ id: 'timer', label: 'Timer (~1ms)' }],
      },
      {
        description: 'Close phase → kết thúc vòng. Vòng mới bắt đầu từ Timers phase. Timer đã hết hạn → setTimeout callback chạy.',
        highlightLines: [5],
        callStack: [{ id: 'st-cb', label: '() => log("setTimeout")' }],
        nextTickQueue: [],
        microtaskQueue: [],
        timerQueue: [],
        checkQueue: [],
        phase: 'timers',
        consoleOutput: ['setImmediate', 'setTimeout'],
        libuvOps: [],
      },
      {
        description: 'Kết quả LUÔN là: setImmediate → setTimeout. Vì trong I/O callback (Poll phase), Check phase luôn chạy trước Timers phase của vòng tiếp theo.',
        highlightLines: [],
        callStack: [],
        nextTickQueue: [],
        microtaskQueue: [],
        timerQueue: [],
        checkQueue: [],
        phase: 'idle',
        consoleOutput: ['setImmediate', 'setTimeout'],
        libuvOps: [],
      },
    ],
  },
]
